### ISSUE TITLE
Classpath

### ISSUE THREAD

**Issue by cpy24** [dthcas/partytime#2]
Through your files, I noticed that you're uploading files to Github. Not that it's anything bad - I do this all the time - but I think you missed a file.

.classpath:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

**Comment by dthcas** [comment]
I am trying to get the project running in Eclipse for testing and as such I generated a class path file. Not sure if this needs uploading to the server. It's a test. First time for me to run a project here. Once I fixed this though, I was able to use the context menus again.

The main problem was that the project in Eclipse is not defined properly when you import from the Git repository. You need to go into the project properties and the change the project type to Java. Then it will recognise the various syntax and check for errors. If anyone needs screenshots please ask and I'll provide.

__________________________________________________
A step in the right direction only takes a moment 🏃

________________________________

**Comment by cpy24** [comment]
Will it help if a standard **project** format is applied to this repository instead of a simple `package`?
![image](https://user-images.githubusercontent.com/56590830/70288929-3372ed00-180e-11ea-8ae0-8c05c288c972.png)

and all the subfolders can be stored into the project:
![image](https://user-images.githubusercontent.com/56590830/70288899-0fafa700-180e-11ea-8e05-b4d2cfe321ba.png)

In this approach, files will be auto-generated and I think this may be the best solution instead of manually creating files. Yes, it may take more time to resconstruct the directory tree, but (1) I think I can fix it and (2) there won't be problems that external files may have

**Comment by dthcas** [comment]
I think I solved this now.  It now should reflect the proper project structure.  Please let me know if it is still a problem.

**Comment by dthcas** [comment]
Structure seems to be more suited for project now.  Please open a new issue if this is still a problem.
