### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by cpy24** [dthcas/partytime#3]
To encourage another format of commenting - through a markdown file, I think that inserting this file will help:

(whatever_name_you_want).md  <-- `.md` file
```markdown
## Welcome to GitHub Pages

You can use the [editor on GitHub](https://github.com/crimsonpython24/apcs/edit/master/README.md) to maintain and preview the content for your website in Markdown files.

Whenever you commit to this repository, GitHub Pages will run [Jekyll](https://jekyllrb.com/) to rebuild the pages in your site, from the content in your Markdown files.

### Markdown

Markdown is a lightweight and easy-to-use syntax for styling your writing. It includes conventions for

```markdown
Syntax highlighted code block

# Header 1
## Header 2
### Header 3

- Bulleted
- List

1. Numbered
2. List

**Bold** and _Italic_ and `Code` text

[Link](url) and ![Image](src)
```

For more details see [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/).

Though this may translate to extra work, I think that this will be more effective because it's better formatted and users don't have to dig through the lines to find the comments. Again, just another suggestion.

**Comment by dthcas** [comment]
Interesting.. I'll look into the markdown file situation and get back to you. Thanks for sharing.

__________________________________________________
A step in the right direction only takes a moment 🏃

________________________________

**Comment by dthcas** [comment]
Feel free to add markdowns, though I'm not sure yet how to use them or what they might be for.  Maybe you can explain in class how they are displayed and the benefit for everyone.  Until then, I'll just comment code the old-fashioned way (cos i'm old)
